baseURL = 'https://YCP-Rev-Metrix.github.io/Wiki/'
languageCode = 'en-us'
title = 'RevMetrix'

theme = "hugo-theme-relearn"

[outputs]
home = [ "HTML", "RSS", "SEARCH", "SEARCHPAGE"]

[params]
disableLandingPageButton = true
themeVariant = "zen-dark"
collapsibleMenu = true
editURL = "https://github.com/YCP-Rev-Metrix/Wiki/edit/main/content/"

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub Organization"
identifier = "ds"
url = "https://github.com/YCP-Rev-Metrix"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-google-drive'></i> Google Drive"
url = "https://drive.google.com/drive/folders/1Z_TtR7IVxIza5YR7sO4sxDVqkagdBix5?usp=drive_link"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "more/credits/"
weight = 30
