baseURL = 'https://bit-of-everything-mc.github.io/Wiki/'
languageCode = 'en-us'
title = 'RevMetrix'

theme = "hugo-theme-relearn"

[outputs]
home = [ "HTML", "RSS", "SEARCH", "SEARCHPAGE"]

[params]
disableLandingPageButton = true
themeVariant = "zen-dark"
collapsibleMenu = true

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub Organization"
identifier = "ds"
url = "https://github.com/YCP-Rev-Metrix"
weight = 10

[[menu.shortcuts]]
name = "<svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M339 314.9L175.4 32h161.2l163.6 282.9H339zm-137.5 23.6L120.9 480h310.5L512 338.5H201.5zM154.1 67.4L0 338.5 80.6 480 237 208.8 154.1 67.4z"/></svg> Google Drive"
url = "https://drive.google.com/drive/folders/1Z_TtR7IVxIza5YR7sO4sxDVqkagdBix5?usp=drive_link"
weight = 11
