baseURL = 'https://bit-of-everything-mc.github.io/Wiki/'
languageCode = 'en-us'
title = 'RTevMetrix'

theme = "hugo-theme-relearn"

[outputs]
home = [ "HTML", "RSS", "SEARCH", "SEARCHPAGE"]

[params]
disableLandingPageButton = true
themeVariant = "zen-dark"
collapsibleMenu = true
